### ISSUE TITLE
[FEATURE REQUEST] minSdk setting in pubspec.yaml to solve issue #324

### ISSUE THREAD

**Issue by Areopagitics** [fluttercommunity/flutter_launcher_icons#330]
### :speech_balloon: Description
The ability to set minSdk setting in pubspec.yaml to solve issue #324. Like this for example:

```
flutter_icons:
  android: true
  image_path: "assets/icon.png"
  minSdk: 16
```

### :question: Platform
Android

**Comment by RatakondalaArun** [comment]
Possibly fixed in #322

**Comment by jakehockey10** [comment]
I'm still seeing this issue.  I have the following:

```
environment:
  sdk: ">=2.16.1"
...
dev_dependencies:
...
  flutter_launcher_icons: ^0.9.3
```

and my build.gradle file has a minSdkVersion of 21.

Here is the output:

``` shell
> flutter pub run flutter_launcher_icons:main
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.3)
  ════════════════════════════════════════════


✓ Successfully generated launcher icons
Unhandled exception:

✗ ERROR: InvalidConfigException
Cannot not find minSdk from android/app/build.gradle or android/local.propertiesSpecify minSdk in either android/app/build.gradle or android/local.properties
#0      createIconsFromConfig (package:flutter_launcher_icons/main.dart:96:7)
#1      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#2      main (file:///C:/Users/Jacob.Smith/Documents/flutter_windows_2.10.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.3/bin/main.dart:7:26)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

Since the error mentions `minSdk` instead of `minSdkVersion` I tried added that with the value set to 21 and that still gave the same error.  I also tried editing the files mentioned in the stacktrace, but that didn't seem to make a difference, so it must be executing versions of these files that are not ACTUALLY in that location.  Either way, I'd like to use this, is there anything I can do in this moment to resolve this?  Thanks.

**Comment by RatakondalaArun** [comment]
This issue is resolved with #392
